package com.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.3
 * 2024-03-24T12:13:46.357+01:00
 * Generated source version: 3.6.3
 *
 */
@WebService(targetNamespace = "http://example.com/", name = "IShipmentService")
@XmlSeeAlso({ObjectFactory.class})
public interface IShipmentService {

    @WebMethod(action = "urn:ProcessShipmentRequest")
    @RequestWrapper(localName = "processShipmentRequest", targetNamespace = "http://example.com/", className = "com.example.ProcessShipmentRequest")
    @ResponseWrapper(localName = "processShipmentRequestResponse", targetNamespace = "http://example.com/", className = "com.example.ProcessShipmentRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.ShipmentDetail processShipmentRequest(

        @WebParam(name = "arg0", targetNamespace = "")
        com.example.ShipmentRequest arg0
    );
}
