
package com.example;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.example.ShipmentServiceService;
import com.example.IShipmentService;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.ws.security.SecurityConstants;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;

/**
 * This class was generated by Apache CXF 3.6.3
 * 2024-03-24T12:13:46.319+01:00
 * Generated source version: 3.6.3
 *
 */
public final class IShipmentService_ShipmentServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://example.com/", "ShipmentServiceService");

    private IShipmentService_ShipmentServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ShipmentServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
        
        ShipmentServiceService ss = new ShipmentServiceService(wsdlURL, SERVICE_NAME);
        IShipmentService port = ss.getShipmentServicePort();
//        WS-SECURITY
        Client client = ClientProxy.getClient(port);
        Map<String, Object> outProps = new HashMap<>();
        outProps.put("action", "UsernameToken");
        outProps.put("user", "Alice");
        outProps.put("passwordType", "PasswordText");
        outProps.put("passwordCallbackClass", "com.example.PasswordHandler");
        
        WSS4JOutInterceptor outInterceptor = new WSS4JOutInterceptor(outProps);
        client.getOutInterceptors().add(outInterceptor);

        {
	        System.out.println("Invoking processShipmentRequest...");
	        com.example.ShipmentRequest _processShipmentRequest_arg0 = new com.example.ShipmentRequest();
	        _processShipmentRequest_arg0.setCustomerId("CustomerId1505877428");
	        com.example.ShipmentDetail _processShipmentRequest_arg0ShipmentDetail = new com.example.ShipmentDetail();
	        _processShipmentRequest_arg0ShipmentDetail.setAddress("Address-845925652");
	        _processShipmentRequest_arg0ShipmentDetail.setItemId("ItemId2084525825");
	        _processShipmentRequest_arg0ShipmentDetail.setQuantity(10);
	        _processShipmentRequest_arg0.setShipmentDetail(_processShipmentRequest_arg0ShipmentDetail);
	        com.example.ShipmentDetail _processShipmentRequest__return = port.processShipmentRequest(_processShipmentRequest_arg0);
	        System.out.println("processShipmentRequest.result=" + _processShipmentRequest__return);
        }

        System.exit(0);
    }

}
