
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.3
 * 2024-03-24T12:13:46.352+01:00
 * Generated source version: 3.6.3
 *
 */

@javax.jws.WebService(
                      serviceName = "ShipmentServiceService",
                      portName = "ShipmentServicePort",
                      targetNamespace = "http://example.com/",
                      wsdlLocation = "http://localhost:8060/cfx-server/services/ShipmentServicePort?wsdl",
                      endpointInterface = "com.example.IShipmentService")

public class ShipmentServicePortImpl implements IShipmentService {

    private static final Logger LOG = Logger.getLogger(ShipmentServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.IShipmentService#processShipmentRequest(com.example.ShipmentRequest arg0)*
     */
    public com.example.ShipmentDetail processShipmentRequest(com.example.ShipmentRequest arg0) {
        LOG.info("Executing operation processShipmentRequest");
        System.out.println(arg0);
        try {
            com.example.ShipmentDetail _return = new com.example.ShipmentDetail();
            _return.setAddress("Address-1812188221");
            _return.setItemId("ItemId-1284060088");
            _return.setQuantity(10);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
