package com.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.3
 * 2024-03-24T12:13:46.359+01:00
 * Generated source version: 3.6.3
 *
 */
@WebServiceClient(name = "ShipmentServiceService",
                  wsdlLocation = "http://localhost:8060/cfx-server/services/ShipmentServicePort?wsdl",
                  targetNamespace = "http://example.com/")
public class ShipmentServiceService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://example.com/", "ShipmentServiceService");
    public static final QName ShipmentServicePort = new QName("http://example.com/", "ShipmentServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8060/cfx-server/services/ShipmentServicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ShipmentServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8060/cfx-server/services/ShipmentServicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ShipmentServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ShipmentServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShipmentServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ShipmentServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ShipmentServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ShipmentServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IShipmentService
     */
    @WebEndpoint(name = "ShipmentServicePort")
    public IShipmentService getShipmentServicePort() {
        return super.getPort(ShipmentServicePort, IShipmentService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IShipmentService
     */
    @WebEndpoint(name = "ShipmentServicePort")
    public IShipmentService getShipmentServicePort(WebServiceFeature... features) {
        return super.getPort(ShipmentServicePort, IShipmentService.class, features);
    }

}
