
package com.example.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.3
 * Sat Mar 23 16:46:36 CET 2024
 * Generated source version: 3.6.3
 */

@XmlRootElement(name = "processShipmentRequestResponse", namespace = "http://example.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processShipmentRequestResponse", namespace = "http://example.com/")

public class ProcessShipmentRequestResponse {

    @XmlElement(name = "return")
    private com.example.ShipmentDetail _return;

    public com.example.ShipmentDetail getReturn() {
        return this._return;
    }

    public void setReturn(com.example.ShipmentDetail new_return)  {
        this._return = new_return;
    }

}

